[package]
name = "xbfisher-station"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0.1", features = ["derive"] }
chrono = "0.4.38"
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0.228", features = ["derive"] }
sysinfo = "0.37.0"
systemstat = "0.2.4"
